// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmq1uvnwywNyrM4wpOLx5qAI08JsJ4xkM',
    appId: '1:908004404464:web:7863ac69b118740d432635',
    messagingSenderId: '908004404464',
    projectId: 'music-app-b74ef',
    authDomain: 'music-app-b74ef.firebaseapp.com',
    storageBucket: 'music-app-b74ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNHmliRzsxR3Jz-R4S5KFQOFf5z1uuDEs',
    appId: '1:908004404464:android:04b44122b2d1800f432635',
    messagingSenderId: '908004404464',
    projectId: 'music-app-b74ef',
    storageBucket: 'music-app-b74ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAlsOjVMhMcHFIewfGUM4xPHQIU_oc63A',
    appId: '1:908004404464:ios:abe7c1580dff5a21432635',
    messagingSenderId: '908004404464',
    projectId: 'music-app-b74ef',
    storageBucket: 'music-app-b74ef.appspot.com',
    iosBundleId: 'com.example.harmony',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAlsOjVMhMcHFIewfGUM4xPHQIU_oc63A',
    appId: '1:908004404464:ios:1b313296f34147d0432635',
    messagingSenderId: '908004404464',
    projectId: 'music-app-b74ef',
    storageBucket: 'music-app-b74ef.appspot.com',
    iosBundleId: 'com.example.harmony.RunnerTests',
  );
}
